# This file is auto-generated by ZagZig Codegen. Do not edit.
# Generated on 01/12/2022 19:10:18 from resnet18 model.

CODEGEN_NETWORKS = {
    "resnet18":
    [
        "Conv_0",
        "Conv_3",
        "Conv_5",
        "Conv_8",
        "Conv_10",
        "Conv_13",
        "Conv_15",
        "Conv_16",
        "Conv_19",
        "Conv_21",
        "Conv_24",
        "Conv_26",
        "Conv_27",
        "Conv_30",
        "Conv_32",
        "Conv_35",
        "Conv_37",
        "Conv_38",
        "Conv_41",
        "Conv_43",
        "Gemm_48",
    ],
}
