#include "test/compiler/AutoGenerated.h"

#include <fstream>

AutoGenerated::AutoGenerated(std::string& model) : Network("autogen", "") {
  // Open the file
  std::string filePath = "test/compiler/networks/" + model + "/params.pb";
  std::fstream input(filePath, std::ios::in | std::ios::binary);
  if (!input) {
    std::cerr << "Failed to open " << filePath << std::endl;
    exit(1);
  }

  // Read the proto
  if (!modelParams.ParseFromIstream(&input)) {
    std::cerr << "Failed to parse " << filePath << std::endl;
    exit(1);
  }
}

SimplifiedParams AutoGenerated::createSimplifiedParams(
    const example::Param& param) {
  SimplifiedParams simplifiedParams;

  // TODO: use proper offsets. for now, we will just use some large offsets
  simplifiedParams.INPUT_OFFSET = 0;
  simplifiedParams.WEIGHT_OFFSET = 512 * 1024;
  simplifiedParams.OUTPUT_OFFSET = 512 * 1024 * 2;
  simplifiedParams.BIAS_OFFSET = 512 * 1024 * 3;
  simplifiedParams.RESIDUAL_OFFSET = 512 * 1024 * 4;

  if (param.has_matrix_param()) {
    example::MatrixParam matrixParam = param.matrix_param();

    // input shape = (B, C, H, W)
    // weight shape = (OC, IC, KH, KW)
    int IC = matrixParam.input().shape(1);
    int IH = matrixParam.input().shape(2);
    int IW = matrixParam.input().shape(3);
    int OC = matrixParam.weight().shape(0);
    int KH = matrixParam.weight().shape(2);
    int KW = matrixParam.weight().shape(3);

    // IH0 * IW0 * OC1 <= 1024
    // (IH0*STRIDE+KH-1) * (IW0*STRIDE+KW-1) <= 1024
    // KH * KW * OC1 * IC0 <= 1024

    int IH0 = 28;
    int IW0 = 28;

    // handle special case for replication

    // dimensions
    std::cout << "Input Dimensions: " << std::endl;

    for (int i = 0; i < matrixParam.input().shape_size(); i++) {
      std::cout << matrixParam.input().shape(i) << " ";
    }
    std::cout << std::endl;
  }

  return simplifiedParams;
}

std::vector<Workload> AutoGenerated::getWorkloadsInRange(
    const std::vector<std::string>& workloadNames) {
  std::vector<Workload> workloads;
  // TODO: make it work for a range of workloads

  std::string workloadName = workloadNames[0];
  for (const example::Param& param : modelParams.params()) {
    std::cout << param.name() << std::endl;

    if (param.has_matrix_param()) {
      std::cout << "Matrix Param" << std::endl;
      example::MatrixParam matrixParam = param.matrix_param();
      std::cout << matrixParam.name() << std::endl;
    }

    if (param.name() == workloadName) {
      Workload workload;
      workload.name = param.name();
      workload.params = createSimplifiedParams(param);
      workloads.push_back(workload);
    }
  }
  return workloads;
}

std::vector<Workload> AutoGenerated::getAllWorkloads() {
  std::vector<Workload> workloads;
  // TODO
  return workloads;
}
