#include "test/compiler/AutoGenerated.h"

#include <fstream>

AutoGenerated::AutoGenerated(std::string& model)
    : model(model), Network("autogen", "") {
  // Open the file
  std::string filePath = "test/compiler/networks/" + model + "/params.pb";
  std::fstream input(filePath, std::ios::in | std::ios::binary);
  if (!input) {
    std::cerr << "Failed to open " << filePath << std::endl;
    exit(1);
  }

  // Read the proto
  if (!modelParams.ParseFromIstream(&input)) {
    std::cerr << "Failed to parse " << filePath << std::endl;
    exit(1);
  }
}

Workload AutoGenerated::createWorkload(const example::Param& param) {
  Workload workload;
  SimplifiedParams simplifiedParams;

  workload.name = param.name();

  if (param.has_matrix_param()) {
    example::MatrixParam matrixParam = param.matrix_param();

    // input shape = (B, C, H, W)
    // weight shape = (OC, IC, KH, KW)
    int IC = matrixParam.input().shape(1);
    int IH = matrixParam.input().shape(2);
    int IW = matrixParam.input().shape(3);
    int OC = matrixParam.weight().shape(0);
    int KH = matrixParam.weight().shape(2);
    int KW = matrixParam.weight().shape(3);

    // TODO: loop tilings are hardcoded for now, ideally we would integrate with
    // a DSE tool like Interstellar

    if (IH == 224 && IW == 224 && IC == 3 && KH == 7 && KW == 7 &&
        OC == 64) {  // conv1
      SimplifiedParams tilingParams = {
          .loops = {{7, 7, 2, 1, 1, 1}, {1, 2, 7, 2, 16, 16}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5},
          .REPLICATION = true};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 64 && KH == 3 && KW == 3 &&
               OC == 64) {  // layer1
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 4, 1, 1, 1}, {4, 1, 3, 3, 28, 28}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 64 && KH == 1 && KW == 1 &&
               OC == 64) {  // layer2_0_downsample
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 4, 1, 1, 1}, {4, 2, 1, 1, 14, 14}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 56 && IW == 56 && IC == 64 && KH == 3 && KW == 3 &&
               OC == 64) {  // layer2
      SimplifiedParams tilingParams = {
          .loops = {{4, 4, 4, 1, 1, 1}, {4, 3, 3, 2, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 64 && KH == 1 && KW == 1 &&
               OC == 128) {  // layer3_0_downsample
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 2, 1, 1, 1}, {8, 8, 1, 1, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 64 && KH == 3 && KW == 3 &&
               OC == 128) {  // layer3
      SimplifiedParams tilingParams = {
          .loops = {{2, 2, 4, 1, 1, 1}, {8, 3, 3, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 64 && KH == 3 && KW == 3 &&
               OC == 128) {  // layer4_0_downsample
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 2, 1, 1, 1}, {16, 16, 1, 1, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 1},
          .fxIndex = 3,
          .fyIndex = 2,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else if (IH == 28 && IW == 28 && IC == 64 && KH == 3 && KW == 3 &&
               OC == 128) {  // layer4
      SimplifiedParams tilingParams = {
          .loops = {{1, 1, 8, 1, 1, 1}, {16, 3, 3, 4, 7, 7}},
          .inputXLoopIndex = {0, 5},
          .inputYLoopIndex = {1, 4},
          .reductionLoopIndex = {3, 0},
          .weightLoopIndex = {2, 3},
          .fxIndex = 2,
          .fyIndex = 1,
          .weightReuseIndex = {4, 5}};
      simplifiedParams = tilingParams;
    } else {
      std::cout << "Tiling has not been hardcoded for this layer yet"
                << std::endl;
      std::cout << "IC: " << IC << " IH: " << IH << " IW: " << IW
                << " OC: " << OC << " KH: " << KH << " KW: " << KW << std::endl;
      exit(1);
    }

    // TODO: use proper offsets. for now, we will just use some large offsets
    simplifiedParams.INPUT_OFFSET = 0;
    simplifiedParams.WEIGHT_OFFSET = 512 * 1024;
    simplifiedParams.OUTPUT_OFFSET = 512 * 1024 * 2;
    simplifiedParams.BIAS_OFFSET = 512 * 1024 * 3;
    simplifiedParams.RESIDUAL_OFFSET = 512 * 1024 * 4;

    assert(matrixParam.stride_size() == 1 ||
           matrixParam.stride()[0] == matrixParam.stride()[1]);
    simplifiedParams.STRIDE = matrixParam.stride()[0];

    workload.files.inputs_file = "test/compiler/networks/" + model +
                                 "/tensor_files/" + matrixParam.input().node() +
                                 ".bin";
    workload.files.weights_file = "test/compiler/networks/" + model +
                                  "/tensor_files/" +
                                  matrixParam.weight().node() + ".bin";
    if (matrixParam.has_bias()) {
      workload.files.bias_file = "test/compiler/networks/" + model +
                                 "/tensor_files/" + matrixParam.bias().node() +
                                 ".bin";
    }
  }

  for (int i = 0; i < param.vector_params_size(); i++) {
    example::VectorParam vectorParam = param.vector_params(i);

    if (vectorParam.opcode() == "vec_add") {
      simplifiedParams.RESIDUAL = true;
      workload.files.residual_file = "test/compiler/networks/" + model +
                                     "/tensor_files/" +
                                     vectorParam.other().node() + ".bin";
    } else if (vectorParam.opcode() == "vec_relu") {
      simplifiedParams.RELU = true;
    } else {
      std::cerr << "Opcode not supported" << std::endl;
      exit(1);
    }
  }

  workload.files.outputs_file = "test/compiler/networks/" + model +
                                "/tensor_files/" + param.name() + ".bin";

  workload.params = simplifiedParams;

  return workload;
}

std::vector<Workload> AutoGenerated::getWorkloadsInRange(
    const std::vector<std::string>& workloadNames) {
  std::vector<Workload> workloads;
  // TODO: make it work for a range of workloads

  std::string workloadName = workloadNames[0];
  for (const example::Param& param : modelParams.params()) {
    std::cout << param.name() << std::endl;

    // if (param.has_matrix_param()) {
    //   std::cout << "Matrix Param" << std::endl;
    //   example::MatrixParam matrixParam = param.matrix_param();
    //   std::cout << matrixParam.name() << std::endl;
    // }

    if (param.name() == workloadName) {
      workloads.push_back(createWorkload(param));
    }
  }
  return workloads;
}

std::vector<Workload> AutoGenerated::getAllWorkloads() {
  std::vector<Workload> workloads;
  // TODO
  return workloads;
}
