#include "test/compiler/AutoGenerated.h"

#include <fstream>

AutoGenerated::AutoGenerated(std::string& model) : Network("autogen", "") {
  // Open the file
  std::string filePath = "test/compiler/networks/" + model + ".pb";
  std::fstream input(filePath, std::ios::in | std::ios::binary);
  if (!input) {
    std::cerr << "Failed to open " << filePath << std::endl;
    exit(1);
  }

  // Read the proto
  if (!modelParams.ParseFromIstream(&input)) {
    std::cerr << "Failed to parse " << filePath << std::endl;
    exit(1);
  }
}

std::vector<Workload> AutoGenerated::getWorkloadsInRange(
    const std::vector<std::string>& workloadNames) {
  std::vector<Workload> workloads;
  // TODO
  return workloads;
}

std::vector<Workload> AutoGenerated::getAllWorkloads() {
  std::vector<Workload> workloads;
  // TODO
  return workloads;
}
