# Hardware settings shared by native builds and Catapult/SCVerify.
export INPUT_BUFFER_SIZE ?= 1024
export WEIGHT_BUFFER_SIZE ?= 1024
export ACCUM_BUFFER_SIZE ?= 1024

# Defaulting these to false matches the #ifndef fallbacks in
# ArchitectureParams.h, so -DX=false and leaving X undefined are equivalent.
export DOUBLE_BUFFERED_ACCUM_BUFFER ?= false
export SUPPORT_MVM ?= false
export SUPPORT_SPMM ?= false
export SUPPORT_DWC ?= false
export MATRIX_BACKEND ?= 0

# Empty external port widths retain ArchitectureParams.h's derived defaults.
export IC_PORT_WIDTH ?=
export OC_PORT_WIDTH ?=

export CIM_MACRO_INPUT_LANES ?= 64
export CIM_MACRO_OUTPUT_LANES ?= 8
export CIM_WEIGHT_SETS ?= 18
export CIM_BASE_A_WIDTH ?= 4
export CIM_BASE_B_WIDTH ?= 4
export CIM_BASE_C_WIDTH ?= 20
export CIM_MACRO_WRITE_INPUT_LANES ?= 1
export CIM_MAC_LATENCY ?= 1
export CIM_MODE ?= 0
export CIM_SIGNED ?= true
export CIM_TILE_INPUT_AXIS_ELEMENTS ?= 1
export CIM_TILE_OUTPUT_AXIS_ELEMENTS ?= 4
export CIM_INPUT_AXIS_TILES ?= 1
export CIM_OUTPUT_AXIS_TILES ?= 1
export CIM_A_PORT_TILES ?= $(CIM_INPUT_AXIS_TILES)
export CIM_B_PORT_TILES ?= $(CIM_OUTPUT_AXIS_TILES)
export CIM_C_PORT_TILES ?= $(CIM_OUTPUT_AXIS_TILES)
export CIM_C_BEAT_LAYOUT ?= 1
export CIM_ARRAY_RESULT_SLOTS ?= $(CIM_INPUT_AXIS_TILES)
export CIM_LOCAL_ACCUM_CONTEXTS ?= 4

ifneq ($(filter $(MATRIX_BACKEND),0 1),$(MATRIX_BACKEND))
$(error MATRIX_BACKEND must be 0 (systolic) or 1 (CIM))
endif

export ARCHITECTURE_PARAMS := IC_DIMENSION OC_DIMENSION IC_PORT_WIDTH \
    OC_PORT_WIDTH INPUT_BUFFER_SIZE WEIGHT_BUFFER_SIZE ACCUM_BUFFER_SIZE \
    DOUBLE_BUFFERED_ACCUM_BUFFER SUPPORT_MVM SUPPORT_SPMM SUPPORT_DWC \
    MATRIX_BACKEND CIM_MACRO_INPUT_LANES CIM_MACRO_OUTPUT_LANES CIM_WEIGHT_SETS \
    CIM_BASE_A_WIDTH CIM_BASE_B_WIDTH CIM_BASE_C_WIDTH \
    CIM_MACRO_WRITE_INPUT_LANES CIM_MAC_LATENCY CIM_MODE CIM_SIGNED \
    CIM_TILE_INPUT_AXIS_ELEMENTS CIM_TILE_OUTPUT_AXIS_ELEMENTS \
    CIM_INPUT_AXIS_TILES CIM_OUTPUT_AXIS_TILES CIM_A_PORT_TILES CIM_B_PORT_TILES \
    CIM_C_PORT_TILES CIM_C_BEAT_LAYOUT CIM_ARRAY_RESULT_SLOTS \
    CIM_LOCAL_ACCUM_CONTEXTS CLOCK_PERIOD
export ARCHITECTURE_DEFINES = -D$(DATATYPE) $(foreach param,$(ARCHITECTURE_PARAMS),\
    $(if $(strip $($(param))),-D$(param)=$($(param))))

# Keep upstream's default systolic names. Encode additional settings when used.
COMMON_BUILD_SUFFIX := $(if $(filter-out false,$(SUPPORT_DWC)),_dwc$(SUPPORT_DWC))
COMMON_BUILD_SUFFIX := $(COMMON_BUILD_SUFFIX)$(if $(strip $(IC_PORT_WIDTH)$(OC_PORT_WIDTH)),_ports$(if $(strip $(IC_PORT_WIDTH)),$(IC_PORT_WIDTH),auto)x$(if $(strip $(OC_PORT_WIDTH)),$(OC_PORT_WIDTH),auto))
COMMON_BUILD_SUFFIX := $(COMMON_BUILD_SUFFIX)$(if $(strip $(CLOCK_PERIOD)),_clock$(CLOCK_PERIOD))

# Literal CIM settings keep different macro and interface configurations apart.
CIM_BUILD_SUFFIX := _cim_macro$(CIM_MACRO_INPUT_LANES)x$(CIM_MACRO_OUTPUT_LANES)_sets$(CIM_WEIGHT_SETS)
CIM_BUILD_SUFFIX := $(CIM_BUILD_SUFFIX)_bits$(CIM_BASE_A_WIDTH)x$(CIM_BASE_B_WIDTH)x$(CIM_BASE_C_WIDTH)_write$(CIM_MACRO_WRITE_INPUT_LANES)
CIM_BUILD_SUFFIX := $(CIM_BUILD_SUFFIX)_latency$(CIM_MAC_LATENCY)_mode$(CIM_MODE)_signed$(CIM_SIGNED)
CIM_BUILD_SUFFIX := $(CIM_BUILD_SUFFIX)_elements$(CIM_TILE_INPUT_AXIS_ELEMENTS)x$(CIM_TILE_OUTPUT_AXIS_ELEMENTS)_tiles$(CIM_INPUT_AXIS_TILES)x$(CIM_OUTPUT_AXIS_TILES)
CIM_BUILD_SUFFIX := $(CIM_BUILD_SUFFIX)_ports$(CIM_A_PORT_TILES)x$(CIM_B_PORT_TILES)x$(CIM_C_PORT_TILES)_layout$(CIM_C_BEAT_LAYOUT)
CIM_BUILD_SUFFIX := $(CIM_BUILD_SUFFIX)_slots$(CIM_ARRAY_RESULT_SLOTS)_contexts$(CIM_LOCAL_ACCUM_CONTEXTS)
BACKEND_BUILD_SUFFIX := $(COMMON_BUILD_SUFFIX)$(if $(filter 1,$(MATRIX_BACKEND)),$(CIM_BUILD_SUFFIX))
BUILD_NAME = $(DATATYPE)_$(IC_DIMENSION)x$(OC_DIMENSION)_$(INPUT_BUFFER_SIZE)x$(WEIGHT_BUFFER_SIZE)x$(ACCUM_BUFFER_SIZE)_$(DOUBLE_BUFFERED_ACCUM_BUFFER)_$(SUPPORT_MVM)_$(SUPPORT_SPMM)$(BACKEND_BUILD_SUFFIX)
