# Defaults mirror src/cim/CIMConfig.h for direct Catapult invocations.
# Make exports the complete configuration through config.mk.
foreach {name value} {
  MATRIX_BACKEND 0
  CIM_MACRO_INPUT_LANES 64
  CIM_MACRO_OUTPUT_LANES 8
  CIM_WEIGHT_SETS 18
  CIM_BASE_A_WIDTH 4
  CIM_BASE_B_WIDTH 4
  CIM_BASE_C_WIDTH 20
  CIM_MACRO_WRITE_INPUT_LANES 1
  CIM_MAC_LATENCY 1
  CIM_MODE 0
  CIM_SIGNED true
  CIM_TILE_INPUT_AXIS_ELEMENTS 1
  CIM_TILE_OUTPUT_AXIS_ELEMENTS 4
  CIM_INPUT_AXIS_TILES 1
  CIM_OUTPUT_AXIS_TILES 1
  CIM_C_BEAT_LAYOUT 1
  CIM_LOCAL_ACCUM_CONTEXTS 4
} {
  if {![info exists $name]} { set $name $value }
}
foreach {name value} [list \
    CIM_A_PORT_TILES $CIM_INPUT_AXIS_TILES \
    CIM_B_PORT_TILES $CIM_OUTPUT_AXIS_TILES \
    CIM_C_PORT_TILES $CIM_OUTPUT_AXIS_TILES \
    CIM_ARRAY_RESULT_SLOTS $CIM_INPUT_AXIS_TILES] {
  if {![info exists $name]} { set $name $value }
}

set MATRIX_BACKEND_SYSTOLIC 0
set MATRIX_BACKEND_CIM 1
if {$MATRIX_BACKEND ni {0 1}} {
  error "MATRIX_BACKEND must be 0 (systolic) or 1 (CIM)"
}
if {[string match CIM* $BLOCK] && $MATRIX_BACKEND != $MATRIX_BACKEND_CIM} {
  error "CIM synthesis targets require MATRIX_BACKEND=1"
}

proc cim_element_template {} {
  global CIM_MACRO_INPUT_LANES CIM_MACRO_OUTPUT_LANES CIM_WEIGHT_SETS \
         CIM_BASE_A_WIDTH CIM_BASE_B_WIDTH CIM_BASE_C_WIDTH \
         CIM_MACRO_WRITE_INPUT_LANES CIM_MAC_LATENCY CIM_MODE \
         INPUT_DTYPE_WIDTH WEIGHT_DTYPE_WIDTH CIM_SIGNED
  return "CIMElement<$CIM_MACRO_INPUT_LANES, $CIM_MACRO_OUTPUT_LANES, $CIM_WEIGHT_SETS, $CIM_BASE_A_WIDTH, $CIM_BASE_B_WIDTH, $CIM_BASE_C_WIDTH, $CIM_MACRO_WRITE_INPUT_LANES, $CIM_MAC_LATENCY, $CIM_MODE, $INPUT_DTYPE_WIDTH, $WEIGHT_DTYPE_WIDTH, $CIM_SIGNED>"
}

proc cim_array_template {} {
  global CIM_MACRO_INPUT_LANES CIM_MACRO_OUTPUT_LANES CIM_WEIGHT_SETS \
         CIM_BASE_A_WIDTH CIM_BASE_B_WIDTH CIM_BASE_C_WIDTH \
         CIM_MACRO_WRITE_INPUT_LANES CIM_MAC_LATENCY CIM_MODE CIM_SIGNED \
         INPUT_DTYPE_WIDTH WEIGHT_DTYPE_WIDTH ACCUM_DATATYPE_WIDTH \
         CIM_TILE_INPUT_AXIS_ELEMENTS CIM_TILE_OUTPUT_AXIS_ELEMENTS \
         CIM_INPUT_AXIS_TILES CIM_OUTPUT_AXIS_TILES CIM_A_PORT_TILES \
         CIM_B_PORT_TILES CIM_C_PORT_TILES CIM_C_BEAT_LAYOUT CIM_ARRAY_RESULT_SLOTS
  return "CIMArray<$CIM_MACRO_INPUT_LANES, $CIM_MACRO_OUTPUT_LANES, $CIM_WEIGHT_SETS, $CIM_BASE_A_WIDTH, $CIM_BASE_B_WIDTH, $CIM_BASE_C_WIDTH, $CIM_MACRO_WRITE_INPUT_LANES, $CIM_MAC_LATENCY, $CIM_MODE, $INPUT_DTYPE_WIDTH, $WEIGHT_DTYPE_WIDTH, $ACCUM_DATATYPE_WIDTH, $CIM_SIGNED, $CIM_TILE_INPUT_AXIS_ELEMENTS, $CIM_TILE_OUTPUT_AXIS_ELEMENTS, $CIM_INPUT_AXIS_TILES, $CIM_OUTPUT_AXIS_TILES, $CIM_A_PORT_TILES, $CIM_B_PORT_TILES, $CIM_C_PORT_TILES, $CIM_C_BEAT_LAYOUT, $CIM_ARRAY_RESULT_SLOTS>"
}

proc cim_processor_template {} {
  global SA_INPUT_TYPE SA_WEIGHT_TYPE ACCUM_DATATYPE ACCUM_BUFFER_DATATYPE \
         SCALE_DATATYPE IC_DIMENSION OC_DIMENSION ACCUM_BUFFER_SIZE \
         CIM_MACRO_INPUT_LANES CIM_MACRO_OUTPUT_LANES CIM_WEIGHT_SETS \
         CIM_BASE_A_WIDTH CIM_BASE_B_WIDTH CIM_BASE_C_WIDTH \
         CIM_MACRO_WRITE_INPUT_LANES CIM_MAC_LATENCY CIM_MODE CIM_SIGNED \
         CIM_TILE_INPUT_AXIS_ELEMENTS CIM_TILE_OUTPUT_AXIS_ELEMENTS \
         CIM_INPUT_AXIS_TILES CIM_OUTPUT_AXIS_TILES CIM_A_PORT_TILES \
         CIM_B_PORT_TILES CIM_C_PORT_TILES CIM_C_BEAT_LAYOUT CIM_ARRAY_RESULT_SLOTS \
         CIM_LOCAL_ACCUM_CONTEXTS
  return "CIMProcessor<InputTypeList, WeightTypeList, $SA_INPUT_TYPE, $SA_WEIGHT_TYPE, $ACCUM_DATATYPE, $ACCUM_BUFFER_DATATYPE, $SCALE_DATATYPE, $IC_DIMENSION, $OC_DIMENSION, $ACCUM_BUFFER_SIZE, $CIM_MACRO_INPUT_LANES, $CIM_MACRO_OUTPUT_LANES, $CIM_WEIGHT_SETS, $CIM_BASE_A_WIDTH, $CIM_BASE_B_WIDTH, $CIM_BASE_C_WIDTH, $CIM_MACRO_WRITE_INPUT_LANES, $CIM_MAC_LATENCY, $CIM_MODE, $CIM_SIGNED, $CIM_TILE_INPUT_AXIS_ELEMENTS, $CIM_TILE_OUTPUT_AXIS_ELEMENTS, $CIM_INPUT_AXIS_TILES, $CIM_OUTPUT_AXIS_TILES, $CIM_A_PORT_TILES, $CIM_B_PORT_TILES, $CIM_C_PORT_TILES, $CIM_C_BEAT_LAYOUT, $CIM_ARRAY_RESULT_SLOTS, $CIM_LOCAL_ACCUM_CONTEXTS>"
}

proc cim_weight_controller_template {} {
  global ACCUM_BUFFER_DATATYPE IC_DIMENSION OC_DIMENSION OC_PORT_WIDTH \
         WEIGHT_DTYPE_WIDTH CIM_MACRO_OUTPUT_LANES CIM_BASE_B_WIDTH \
         CIM_MACRO_WRITE_INPUT_LANES CIM_TILE_OUTPUT_AXIS_ELEMENTS \
         CIM_B_PORT_TILES CIM_WEIGHT_SETS
  set row_width [expr {$OC_DIMENSION * $WEIGHT_DTYPE_WIDTH}]
  set element_outputs [expr {$CIM_MACRO_OUTPUT_LANES / ($WEIGHT_DTYPE_WIDTH / $CIM_BASE_B_WIDTH)}]
  set beat_width [expr {$CIM_MACRO_WRITE_INPUT_LANES * $CIM_B_PORT_TILES * $CIM_TILE_OUTPUT_AXIS_ELEMENTS * $element_outputs * $WEIGHT_DTYPE_WIDTH}]
  return "CIMWeightController<WeightTypeList, $ACCUM_BUFFER_DATATYPE, $IC_DIMENSION, $OC_DIMENSION, $OC_PORT_WIDTH, $row_width, $beat_width, $CIM_WEIGHT_SETS>"
}
