// clang-format off
#ifndef VOYAGER_ADDRESS_H
#define VOYAGER_ADDRESS_H

#define VOYAGER_MMIO_BASE_ADDRESS 0x20000000L

// --- Global / Accelerator Registers ---
#define VOYAGER_BASE_ADDR       (VOYAGER_MMIO_BASE_ADDRESS + 0x000)
#define ACCELERATOR_CYCLE_COUNT (VOYAGER_MMIO_BASE_ADDRESS + 0x008)
#define ACCELERATOR_RUNNING     (VOYAGER_MMIO_BASE_ADDRESS + 0x010)
#define BANK_0_LOADED           (VOYAGER_MMIO_BASE_ADDRESS + 0x01A)
#define BANK_1_LOADED           (VOYAGER_MMIO_BASE_ADDRESS + 0x01B)
#define VOYAGER_INT_STATUS      (VOYAGER_MMIO_BASE_ADDRESS + 0x020)
#define VOYAGER_INT_ENABLE      (VOYAGER_MMIO_BASE_ADDRESS + 0x028)

// --- Matrix Unit Registers ---
#define MATRIX_UNIT_PARAMS_IN   (VOYAGER_MMIO_BASE_ADDRESS + 0x100)
#define MATRIX_UNIT_CYCLE_COUNT (VOYAGER_MMIO_BASE_ADDRESS + 0x108)
#define MATRIX_UNIT_OP_INFLIGHT (VOYAGER_MMIO_BASE_ADDRESS + 0x110)
#define MATRIX_UNIT_WAIT_EN     (VOYAGER_MMIO_BASE_ADDRESS + 0x118)
#define MATRIX_UNIT_WAIT_ID     (VOYAGER_MMIO_BASE_ADDRESS + 0x120)

// --- Vector Unit Registers ---
#define VECTOR_UNIT_PARAMS_IN   (VOYAGER_MMIO_BASE_ADDRESS + 0x200)
#define VECTOR_UNIT_CYCLE_COUNT (VOYAGER_MMIO_BASE_ADDRESS + 0x208)
#define VECTOR_UNIT_OP_INFLIGHT (VOYAGER_MMIO_BASE_ADDRESS + 0x210)
#define VECTOR_UNIT_WAIT_EN     (VOYAGER_MMIO_BASE_ADDRESS + 0x218)
#define VECTOR_UNIT_WAIT_ID     (VOYAGER_MMIO_BASE_ADDRESS + 0x220)

// --- Matrix Vector Unit (MVM) Registers ---
#define MVM_UNIT_PARAMS_IN      (VOYAGER_MMIO_BASE_ADDRESS + 0x300)
#define MVM_UNIT_CYCLE_COUNT    (VOYAGER_MMIO_BASE_ADDRESS + 0x308)
#define MVM_UNIT_OP_INFLIGHT    (VOYAGER_MMIO_BASE_ADDRESS + 0x310)
#define MVM_UNIT_WAIT_EN        (VOYAGER_MMIO_BASE_ADDRESS + 0x318)
#define MVM_UNIT_WAIT_ID        (VOYAGER_MMIO_BASE_ADDRESS + 0x320)

// --- Sparse Matrix-Matrix Unit (SpMM) Registers ---
#define SPMM_UNIT_PARAMS_IN     (VOYAGER_MMIO_BASE_ADDRESS + 0x400)
#define SPMM_UNIT_CYCLE_COUNT   (VOYAGER_MMIO_BASE_ADDRESS + 0x408)
#define SPMM_UNIT_OP_INFLIGHT   (VOYAGER_MMIO_BASE_ADDRESS + 0x410)
#define SPMM_UNIT_WAIT_EN       (VOYAGER_MMIO_BASE_ADDRESS + 0x418)
#define SPMM_UNIT_WAIT_ID       (VOYAGER_MMIO_BASE_ADDRESS + 0x420)

// --- Memory ---
#define SRAM_BASE (0x40000000L)

// Bit definitions
#define INT_BANK0 (1 << 0)
#define INT_BANK1 (1 << 1)
#define INT_DONE  (1 << 2)

#endif // VOYAGER_ADDRESS_H
// clang-format on
