set DIMENSION 16

# set IO_DATATYPE "ac_int<8,true>"
# set ACCUM_DATATYPE "ac_int<32,true>"
# set ACCUM_DATATYPE_WIDTH 32

# set IO_DATATYPE "P8"
# set IO_DATATYPE_DEC "P8D"
# set ACCUM_DATATYPE "P16"
# set INTERMEDIATE_DATATYPE "P16D"
set C_DATA_REP_NAME "bits"

set IO_DATATYPE "F8"
set ACCUM_DATATYPE "F16"
set INTERMEDIATE_DATATYPE "F16"
set C_DATA_REP_NAME "float_val.d"

set ACCUM_DATATYPE_WIDTH 16

set IO_DATATYPE_WIDTH 8
