set DIMENSION 16

# set IO_DATATYPE "ac_int<8,true>"
# set ACCUM_DATATYPE "ac_int<32,true>"
# set ACCUM_DATATYPE_WIDTH 32

set IO_DATATYPE "Posit<8,1,8,16>"
set ACCUM_DATATYPE "Posit<16,1,8,16>"
set INTERMEDIATE_DATATYPE "PositFP<8,16>"
set ACCUM_DATATYPE_WIDTH 16

set IO_DATATYPE_WIDTH 8
