#define INPUT_DATATYPE ac_int<8, true>
#define WEIGHT_DATATYPE ac_int<8, true>
#define OUTPUT_DATATYPE ac_int<8, true>

#define DIMENSION 16
#define INPUT_BUFFER_SIZE 10240
#define WEIGHT_BUFFER_SIZE 10240
#define ACCUMULATION_BUFFER_SIZE 10240